name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # test:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Setup PHP
  #     uses: shivammathur/setup-php@v2
  #     with:
  #       php-version: '8.0'
    
  #   - name: Install dependencies
  #     run: |
  #       composer update --optimize-autoloader
  #       composer install --optimize-autoloader
    
  #   - name: Code Quality Check
  #     run: |
  #       # PHPStan static analysis
  #       if [ -f "vendor/bin/phpstan" ]; then
  #         vendor/bin/phpstan analyse --error-format=github
  #       else
  #         echo "PHPStan not installed, skipping static analysis"
  #       fi
    
  #   - name: Run tests
  #     run: php artisan test

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd ${{ secrets.PROJECT_PATH }} &&
          git pull origin master &&
          composer install --no-dev --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan config:clear &&
          php artisan cache:clear &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan view:cache &&
          sudo systemctl restart apache2 || sudo systemctl restart nginx
        "
